Update the Makefile and added the scripts

diff --git a/scripts/handle-user-data b/scripts/handle-user-data
--- a/scripts/handle-user-data
+++ b/scripts/handle-user-data
@@ -1,8 +1,8 @@
 #!/bin/sh
 
-LABEL=boot2docker-data
+LABEL=b2d-data
 MAGIC="boot2docker, please format-me"
-UNPARTITIONED_HD=/dev/sda
+UNPARTITIONED_HD="/dev/$(lsblk | grep disk | grep ".*da" | cut -f1 -d' ')"
 
 # Function to mount partitions
 mount_partitions() {
@@ -23,29 +23,40 @@ mount_partitions() {
 
     # Just in case, the links will fail if not
     umount -f /var/lib/docker || true
-    rm -rf /var/lib/docker /var/lib/boot2docker /etc/docker /var/lib/minishift
+    rm -rf /var/lib/docker /var/lib/boot2docker /var/lib/minishift /opt
 
     # Detected a disk with a normal linux install (/var/lib/docker + more))
     if [ ! -d "/var/lib" ]; then
         mkdir -p /var/lib
     fi
 
+    if [ -d "/etc/pki/consumer" ]; then
+        rm -fr /etc/pki/consumer /etc/pki/entitlement /etc/pki/product
+        mkdir -p /mnt/$PARTNAME/etc/pki/{consumer,entitlement,product}
+        ln -s /mnt/$PARTNAME/etc/pki/consumer /etc/pki/consumer
+        ln -s /mnt/$PARTNAME/etc/pki/entitlement /etc/pki/entitlement
+        ln -s /mnt/$PARTNAME/etc/pki/product /etc/pki/product
+    fi
+
     mkdir -p /mnt/$PARTNAME/var/lib/docker
-    ln -s /mnt/$PARTNAME/var/lib/docker /var/lib/docker
+    mkdir -p /var/lib/docker
+    mount --bind /mnt/$PARTNAME/var/lib/docker /var/lib/docker
+    restorecon -R /var/lib/docker
 
     mkdir -p /mnt/$PARTNAME/var/lib/boot2docker
-    ln -s /mnt/$PARTNAME/var/lib/boot2docker /var/lib/boot2docker
-
-    mkdir -p /mnt/$PARTNAME/var/lib/boot2docker/etc/docker
-    ln -s /mnt/$PARTNAME/var/lib/boot2docker/etc/docker /etc/docker
+    mkdir -p /var/lib/boot2docker
+    mount --bind /mnt/$PARTNAME/var/lib/boot2docker /var/lib/boot2docker
 
     mkdir -p /mnt/$PARTNAME/var/lib/minishift
-    ln -s /mnt/$PARTNAME/var/lib/minishift /var/lib/minishift
+    mkdir -p /var/lib/minishift
+    mount --bind /mnt/$PARTNAME/var/lib/minishift /var/lib/minishift
 
-    # Make sure /tmp is on the disk too
-    rm -rf /mnt/$PARTNAME/tmp || true
-    mv /tmp /mnt/$PARTNAME/tmp
-    ln -fs /mnt/$PARTNAME/tmp /tmp
+    mkdir -p /mnt/$PARTNAME/var/lib/origin
+    mkdir -p /var/lib/origin
+    mount --bind /mnt/$PARTNAME/var/lib/origin /var/lib/origin
+
+    mkdir -p /mnt/$PARTNAME/opt
+    ln -s /mnt/$PARTNAME/opt /opt
 
     # Move userdata to persistent storage
     if [ -e "/userdata.tar" ]; then
@@ -71,7 +82,7 @@ prepare_partions() {
     # wait for the partition to actually exist, timeout after about 5 seconds
     local timer=0
     while [ "$timer" -lt 10 -a ! -b "${UNPARTITIONED_HD}2" ]; do
-    	timer=$((timer + 1))
+        timer=$((timer + 1))
         sleep 0.5
     done
 
@@ -85,25 +96,25 @@ prepare_partions() {
     # wait for the partition to actually exist, timeout after about 5 seconds
     timer=0
     while [ "$timer" -lt 10 -a ! -b "${UNPARTITIONED_HD}1" ]; do
-    	timer=$((timer + 1))
+        timer=$((timer + 1))
         sleep 0.5
     done
 
     BOOT2DOCKER_DATA=`echo "${UNPARTITIONED_HD}1"`
-    mkfs.ext4 -i 8192 -L $LABEL $BOOT2DOCKER_DATA
+    mkfs.xfs -n ftype=1 -i size=2048 -L $LABEL $BOOT2DOCKER_DATA
 }
 
 # Function to extract userdata.tar containing the ssh keys into the home directory /home/docker
 handle_user_data() {
-	# Extract the userdata into docker user home directory
-	if [ -e "/var/lib/boot2docker/userdata.tar" ]; then
-		tar xf /var/lib/boot2docker/userdata.tar -C /home/docker/ > /var/log/userdata.log 2>&1
-    	rm -f '/home/docker/boot2docker, please format-me'
-		chown -R docker:docker /home/docker/.ssh
-	else
-		echo "Unable to find userdata.tar"
-		exit 1
-	fi
+    # Extract the userdata into docker user home directory
+    if [ -e "/var/lib/boot2docker/userdata.tar" ]; then
+        tar xf /var/lib/boot2docker/userdata.tar -C /home/docker/ > /var/log/userdata.log 2>&1
+        rm -f '/home/docker/boot2docker, please format-me'
+        chown -R docker:docker /home/docker/.ssh
+    else
+        echo "Unable to find userdata.tar"
+        exit 1
+    fi
 }
 
 # TODO Need to make sure to have /sbin on the PATH. Is there a better way?
@@ -116,18 +127,19 @@ echo 'PATH=$PATH:/sbin' >> /home/docker/.bashrc
 # userdata.tar. Remember, /home/docker is not persistent
 BOOT2DOCKER_DATA=`blkid -o device -l -t LABEL=$LABEL`
 if [ -n "$BOOT2DOCKER_DATA" ]; then
-	mount_partitions
-	handle_user_data
-	exit 0
+    mount_partitions
+    handle_user_data
+    exit 0
 fi
 
 # Test for our magic string (it means that the disk was made by ./boot2docker init)
 HEADER=`dd if=$UNPARTITIONED_HD bs=1 count=${#MAGIC} 2>/dev/null`
 if [ "$HEADER" = "$MAGIC" ]; then
-	# Read /userdata.tar with ssh keys and place it temporarily under /
-	dd if=/dev/sda of=/userdata.tar bs=1 count=4096 2>/dev/null
+    # Read /userdata.tar with ssh keys and place it temporarily under /
+    dd if=$UNPARTITIONED_HD of=/userdata.tar bs=1 count=4096 2>/dev/null
 
     prepare_partions
     mount_partitions
     handle_user_data
+    exit 0
 fi
